config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "about-us", to: "about#index", as: :about
  
  get "sign_up", to: "registrations#new", as: :sign_up
  post "sign_up", to: "registrations#create"
  get "login", to: "registrations#login"
  post "login", to: "registrations#login_user"
  delete "logout", to: "sessions#destroy"

#   Pasowrd
  get "edit_password", to: "passwords#edit"
  patch "edit_password", to: "passwords#edit_password" 

	#   omni-auth
  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter
  resources :tweets
  
  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 250}
  validates :published_at, presence: true


  after_initialize do
	self.published_at ||= 24.hours.from_now
  end


  def published?
	tweet_id?
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets

  validates :username, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :twitter_accounts
	has_many :tweets

	validates :email, presence: true 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user

	def set_current_user
		session_id = session[:user_id]
		if session_id
			Current.user = User.find_by(id: session_id)
			Rails.logger.info Current.user
		end
	end

	def require_user_logged_in!
		if Current.user.nil?
			redirect_to login_path, notice: "You need to sign in "
		end
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController 
	# def index
	# 	session_id = session[:user_id]
	# 	if session_id
	# 		@user = User.find_by(id: session_id)
	# 		flash.now[:notice] = "Logged In successfully"
	# 	end
	# end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
	before_action :require_user_logged_in!

	def twitter

		oa = omniauth_params.info
		Rails.logger.info oa
		oa_credentials = omniauth_params.credentials
		new_user = Current.user.twitter_accounts.where(username: oa.nickname).first_or_initialize
		new_user.update(
			name: oa.name,
			username: oa.nickname,
			image: oa.image,
			token: oa_credentials.token,
			secret: oa_credentials.secret,
		)
		if new_user
			redirect_to twitter_index_path, notice: "Twitter account successfully linked"
		else
			redirect_to root_path, notice: "Error connecting to twitter account"
		end
	end

	def omniauth_params
		request.env['omniauth.auth']
	end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
	before_action :require_user_logged_in!

	def edit
	end

	def edit_password
		if Current.user.update(edit_password_params)
			redirect_to root_path, notice: "Password edited successfully"
		else
			render :edit
		end
	end

	def edit_password_params
		params.require(:user).permit(:password, :password_confirmation)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@user = User.new
	end

	def login
		@user = User.new
	end

	def login_user
		selected_user = User.find_by(email: login_params[:email])
		if selected_user && selected_user.authenticate(login_params[:password])
			session[:user_id] = selected_user.id
			redirect_to root_path, notice: "Logged in successfully"
		else
			flash[:notice] = "Error login in user"
			redirect_to :login
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Successfully create user"
		else
			flash[:notice] = "Error saving user"
			render :new
		end
	end

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

	def login_params
		params.require(:user).permit(:email, :password, )
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Logout successfully"
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :require_user_logged_in!
	before_action :set_user_tweets, only: [:index, :new, :create, :destroy]

	def index
	end

	def new
		@tweet = Tweet.new
	end
	def create
		@tweet = Current.user.tweets.new(create_tweet_params)

		if @tweet.save
			redirect_to tweets_path, notice: "Tweet scheduled successfully"
		else
			render :new
		end

	end

	def destroy
		tweet = @user_tweets.find(params[:id])
		if tweet.destroy
			redirect_to tweets_path, notice: "Tweet deleted successfully"
		else
			redirect_to tweets_path, notice: "Error deleting tweet"
		end
	end

	def create_tweet_params
		params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
	end


	private 
	def set_user_tweets
		@user_tweets = Current.user.tweets
		@twitter_accounts = Current.user.twitter_accounts
	end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
	before_action :require_user_logged_in!
	before_action :set_current_tweet_account, only: [:destroy]

	def index
		@twitter_accounts = Current.user.twitter_accounts
	end
	def destroy
		if @twitter_account.destroy
			redirect_to twitter_index_path, notice: "Successfully deleted twitter account"
		else
			render :index
		end
	end

	private
	 def set_current_tweet_account
		@twitter_account = Current.user.twitter_accounts.find( params[:id])
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div>
	<h1>About</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullTutotial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render partial: 'shared/navbar' %>


    <main class="container mx-auto mt-10">
		<%= render partial: "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<div>
<% if @user %>
	<p>Logged in as <%= @user.email %></p>
<% end %>
<h1>Home</h1>

</div>

app/views/partials/_connect_twitter.html.erb
	<%= form_tag('/auth/twitter', method: 'post', data: {turbo: false}) do %>
		<button type='submit' class="btn-primary">Add Account</button>
	<% end %>

app/views/partials/_form_errors.erb
<% if form.object.errors.any? %>
				<div class= "bg-red-500 text-white py-3 px-4 rounded-sm mb-4 gap-2" >
				<%  form.object.errors.full_messages.each do |e| %>
					<p><%= e %><p>
				<% end %>
				</div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<div class= "bg-green-500 text-white py-3 px-4 rounded-sm mb-4" >
		<%= flash[:notice] %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="bg-black flex justify-between py-6 px-6 text-white">
<div class="flex items-center gap-4">
<%= link_to "Rails Twitter", root_path, class: "text-lg font-bold"  %>
<%= link_to "Tweets", tweets_path  %>
<%= link_to "About", about_path  %>
<%= link_to "Twitter Accounts", twitter_index_path  %>
</div>
<div class="flex items-center gap-3">

<% if Current.user.present? && Current.user[:id].present? %>
<p><%= link_to Current.user.email, edit_password_path %></p>
<%= button_to "Log out", logout_path, method: :delete, class: "bg-white text-black rounded-md py-3 px-6"  %>
<% else %>
<%= link_to "Sign up", sign_up_path  %>
<%= link_to "Login", login_path  %>
<% end %>
</div>
</div>

app/views/tweets/index.html.erb
<div>
	<section class="flex items-center justify-between">
		<h1 class="text-lg font-bold" >Tweets</h1>
		<% if @twitter_accounts.any? %>
			<%= link_to "Schedule Tweet", new_tweet_path, class: "btn-primary" %>
		<% else %>
			<%= render 'partials/connect_twitter' %>
		<% end %>
	</section>
	<section class="mt-8 grid grid-cols-3 gap-4">
	<% @user_tweets.each do |tweet| %>
	<div class="border group px-4 py-4 rounded-sm hover:bg-blue-500 hover:!text-white transition-all duration-500 cursor-pointer">
	<div class="flex items-center justify-between">
		<div class="flex items-center gap-2">
			<img src= <%= tweet.twitter_account.image %> class="h-5 w-5 rounded-full"   />
			<%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank , class: "text-sm group-hover:underline " %>
		</div>
			<%= button_to "Delete", tweet_path(id: tweet.id), method: :delete, form: {data: { turbo_confirm: "Are you sure"} } ,
			class: "bg-red-500 text-white py-1 px-2 rounded-md text-xs" %>
		</div>
		<p class="text-lg font-bold mt-2"> <%= tweet.body %> <p>
		<div class="flex items-center gap-2 text-xs  text-gray-500 group-hover:!text-white transition-all duration-500" >
		<p > <%= tweet.published_at %> <p>
		| 
		<% if tweet.published? %>
			<%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank, class: "bg-green-500 text-white py-1 px-2 rounded-md" %>
		<% else %>
			<p class="bg-orange-500 text-white py-1 px-2 rounded-md">Not Published</p>
		<% end %>
		</div>
	</div>
	<% end %>
	</section>
</div>

app/views/tweets/new.html.erb
<%= form_with model: @tweet do |form|  %>
	
		<% if @tweet.errors.any? %>
				<div class= "bg-red-500 text-white py-3 px-4 rounded-sm mb-4 gap-2" >
				<%  @tweet.errors.full_messages.each do |e| %>
					<p><%= e %><p>
				<% end %>
				</div>
		<% end %>
<div class="mt-4 space-y-6">
			<div>
			<%= form.label :twitter_account_id %>
			<%= form.collection_select :twitter_account_id, @twitter_accounts, :id, :username, {} ,{class: "input-field", placeholder: "Select twitter account"} %>
			</div>
			<%= render 'partials/connect_twitter' %>

			<div>
			<%= form.label :body %>
			<%= form.text_area :body, class: "input-field", placeholder: "Enter tweet" %>
			</div>
			<div>
			<%= form.label :published_at %>
			<%= form.datetime_select :published_at, class: "input-field", placeholder: "Select date" %>
			</div>
			 <%= form.submit  "Schedule Tweet" , class: "btn-primary" %>
</div>
<% end %>

app/views/twitter/index.html.erb
<div>
	<section class="flex items-center justify-between">
		<h1 class="text-lg font-bold" >Twitter Accounts</h1>
		<%= render 'partials/connect_twitter' %>
	</section>
	<ul class="space-y-x  p-0">
		<% !@twitter_accounts.nil? && @twitter_accounts.each do |twitter| %>

		<li class="flex items-center gap-2">
		<img src=<%= twitter.image %> alt="profile-image"  class="h-10 w-10 rounded-full overflow-hidden" />
		<%= link_to "@#{twitter.username}", "https://twitter.com/#{twitter.username}", target: :_blank    %>

	
		<%= button_to "Disconnect", twitter_path(id: twitter.id), method: :delete, form: {
			data: { turbo_confirm: "Are you sure"}
		},  class: "btn-primary" %>
		</li>
		<% end %>
	</section>
</div>